apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      module: rabbitmq
  template:
    metadata:
      name: rabbit
      labels:
        module: rabbitmq
    spec:
      containers:
        - name: rabbit-container
          imagePullPolicy: IfNotPresent
          image: rabbitmq:4.2.2-management
          ports:
            - containerPort: 5672
          env:
            - name: SEED_USERNAME
#              value: dmitryl
              valueFrom:
                secretKeyRef:
                  name: rmq-secrets
                  key: SEED_USERNAME
            - name: SEED_USER_PASSWORD
#              value: test
              valueFrom:
                secretKeyRef:
                  name: rmq-secrets
                  key: SEED_USER_PASSWORD
            - name: RABBITMQ_DEFAULT_USER
#              value: dmitryl
              valueFrom:
                secretKeyRef:
                  name: rmq-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
#              value: test
              valueFrom:
                secretKeyRef:
                  name: rmq-secrets
                  key: RABBITMQ_DEFAULT_PASS
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
