apiVersion: v1
kind: Secret
metadata:
  name: rmq-secrets
type: Opaque
data:
  SEED_USERNAME: ZG1pdHJ5bA==           # dmitryl
  SEED_USER_PASSWORD: dGVzdA==          # test
  RABBITMQ_DEFAULT_USER: ZG1pdHJ5bA==   # dmitryl
  RABBITMQ_DEFAULT_PASS: dGVzdA==       # test